name: Build Expo Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Build web app
        run: npx expo export --platform web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-web-build
          path: dist/_expo/static/js/web/
